import Foundation
let id = UUID(uuidString: "11111111-1111-1111-1111-111111111111")!
let date = Date(timeIntervalSince1970: 0)
let source = AgentHandoffSource(id: id, title: "Launch idea", text: String(repeating: "x", count: 7000), date: date)
let related = AgentHandoffSource(id: UUID(), title: "Project decision", text: "Keep recording first.", date: date)
let offline = AgentHandoffBrief(primary: source, project: "Orbit", related: [related], connected: false)
let prompt = offline.prompt(work: .build, request: "Build a landing page")
precondition(prompt.contains("## My request\nBuild a landing page"))
precondition(prompt.contains("Project: Orbit"))
precondition(prompt.contains("Keep recording first."))
precondition(prompt.contains("Excerpt truncated"))
precondition(!prompt.contains(String(repeating: "x", count: 6001)))
precondition(prompt.contains("not connected"))
precondition(prompt.contains("does not authorize publishing"))
precondition(prompt.contains("planned work distinct from completed work"))
let online = AgentHandoffBrief(primary: source, project: nil, related: [], connected: true).prompt(work: .plan, request: " ")
precondition(online.contains(AgentHandoffWork.plan.request))
precondition(online.contains("call get_note with id " + id.uuidString))
precondition(!online.contains("Related project context"))
print("PASS: actual brief formatter — request, project context, truncation, access states, source IDs, and completion boundaries")
